# Test HTTP requests
### use with: REST Client extension
@apiurl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNCwidXNlcm5hbWUiOiJyZWV0dGthakBtZXRyb3BvbGlhLmZpIiwiZW1haWwiOiJyZWV0dGthakBtZXRyb3BvbGlhLmZpIiwiY3JlYXRlZF9hdCI6IjIwMjYtMDMtMzBUMDc6MzU6NTguMDAwWiIsInVzZXJfbGV2ZWwiOiJyZWd1bGFyIiwiaWF0IjoxNzc1Mzc2NTgzLCJleHAiOjE3NzU0NjI5ODN9.xO-wae3RhJI97zPTGvEkqMa6751IhbZIkeV5ESXNxjU"

GET {{apiurl}}/items/1

### Add new item
POST {{apiurl}}/items
Content-Type: application/json

{"name": "Mandariini", "weight": 86}

### Delete item with id 2
DELETE {{apiurl}}/items/2

### Update item with id 1
PUT {{apiurl}}/items/1
Content-Type: application/json

{"name": "updated Omena"}

##############################
### users endpoints

### Get all users (with token)
GET {{apiurl}}/users
Authorization: Bearer {{token}}

### Get all users (FAIL without token)
GET {{apiurl}}/users

### Register new user
POST {{apiurl}}/users
Content-Type: application/json

{
  "username": "reettkaj@metropolia.fi",
  "password": "Fenix184!",
  "email": "reettkaj@metropolia.fi"
}

### Register new user FAIL (email missing) - täytyy laittaa omat kubios sovelluksen tunnarit
POST {{apiurl}}/users
Content-Type: application/json

{
  "username": "",
  "password": ""
}

### User login - täytyy laittaa omat kubios sovelluksen tunnarit
POST {{apiurl}}/users/login
Content-Type: application/json

{
  "username": "",
  "password": ""
}

### Get user info by token
GET {{apiurl}}/users/me
Authorization: Bearer {{token}}


##############################
### Diary entry endpoints

### Get all entries (by user id in token)
GET {{apiurl}}/entries
Authorization: Bearer {{token}}

### Get entry by id
GET {{apiurl}}/entries/6

### Delete entry by id
DELETE {{apiurl}}/entries/9
Authorization: Bearer {{token}}

### Post new entry
POST {{apiurl}}/entries
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "entry_date": "2026-02-04",
  "mood": "really happy",
  "weight": 66,
  "sleep_hours": 5,
  "notes": "normipäivä"
}


### Get Kubios data
GET {{apiurl}}/kubios/user-data
Authorization: Bearer {{token}}
